-- Migración 001: Agregar rol a usuarios
-- Ejecuta estos comandos en PostgreSQL:

-- 1. Verificar si la columna 'rol' existe, si no, añadirla
ALTER TABLE usuarios 
ADD COLUMN IF NOT EXISTS rol VARCHAR(50) DEFAULT 'usuario';

-- 2. Asegurar que la contraseña tenga suficiente espacio para bcrypt
-- bcrypt genera hashes de 60 caracteres, así que aumentamos a 255
ALTER TABLE usuarios 
ALTER COLUMN contrasena TYPE VARCHAR(255);

-- 3. Crear índice en email para búsquedas más rápidas
CREATE INDEX IF NOT EXISTS idx_usuarios_email ON usuarios(email);

-- 4. Ver la estructura actualizada (opcional)
-- \d usuarios
--actualizada
-- Tabla de libros del catálogo global
CREATE TABLE IF NOT EXISTS libros (
  id               SERIAL PRIMARY KEY,
  titulo           VARCHAR(255)  NOT NULL,
  autor            VARCHAR(255)  NOT NULL,
  total_paginas    INTEGER       NOT NULL CHECK (total_paginas > 0),
  descripcion      TEXT,
  genero           VARCHAR(100),
  anio_publicacion INTEGER       CHECK (anio_publicacion BETWEEN 1000 AND 2100),
  imagen_url       TEXT,
  creado_en        TIMESTAMP     NOT NULL DEFAULT NOW(),
  actualizado_en   TIMESTAMP     NOT NULL DEFAULT NOW()
);

-- Trigger para actualizar automaticamente actualizado_en
CREATE OR REPLACE FUNCTION actualizar_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.actualizado_en = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_actualizar_libros
  BEFORE UPDATE ON libros
  FOR EACH ROW
  EXECUTE FUNCTION actualizar_timestamp();

-- Indices para búsquedas frecuentes
CREATE INDEX IF NOT EXISTS idx_libros_titulo ON libros (titulo);
CREATE INDEX IF NOT EXISTS idx_libros_autor  ON libros (autor);
--favoritos
CREATE TABLE favoritos (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INT NOT NULL,
    libro_id VARCHAR(255) NOT NULL,
    creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    -- Restricción para que un usuario no repita el mismo libro en favoritos
    CONSTRAINT unico_usuario_libro UNIQUE (usuario_id, libro_id),
    
    -- Llave foránea vinculada a la tabla usuarios
    CONSTRAINT fk_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE
);